# home
POST: http://192.168.1.116:8080/api/v1/app/interface/uploadEvent

OM: f_weights/highway-sim.om
EX: f_weights/ckpt.om
NAME: f_names/highway.names

MODEL_WIDTH: 608
MODEL_HEIGHT: 608
NMS_THRESHOLD_CONST: 0.65
CLASS_SCORE_CONST: 0.6

# 0. 异常停车
# 1. 行人
# 2. 抛撒物
# 3. 异常行驶
p0: '2'
p1: 'IllegalPark'
p2: '3'
p3: '1'